development:
  adapter: postgresql
  database: nl_development
  encoding: unicode
  pool: 2

test:
  adapter: postgresql
  database: nl_test
  encoding: unicode
  pool: 2

production:
  username: postgres
  host: localhost
  adapter: postgresql
  database: nl_production
  encoding: unicode
  pool: 4
